spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  #
  shell:
    interactive:
      enabled: true

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    #initialization-mode: always
    #platform: postgres

#
messages:
  language: "en"
  country: "GB"
  bundle: "/messages/app_message"
# DB access
