### genre list
GET localhost:8080/genre
Accept: application/json

### genre add
POST localhost:8080/genre
Content-Type: application/json

{
    "name":"GenreName.TestRest",
    "description":"GenreDescription.TestRest"
}

### flux genre list - error
GET localhost:8080/flux/genre
Accept: application/json

### flux genre list - ok
GET localhost:8080/flux/genre
Accept: text/event-stream

### flux genre id
GET localhost:8080/flux/genre/1
Accept: application/json

### flux genre add
POST localhost:8080/flux/genre
Content-Type: application/json

{
  "name":"GenreName.TestFluxRest",
  "description":"GenreDescription.TestFluxRest"
}

### author list
GET localhost:8080/author
Accept: application/json


#### author add
POST localhost:8080/author
Content-Type: application/json

{
  "firstName": "Firstname.TestRest",
  "lastName": "Lastname.TestRest",
  "surName": "Surname.TestRest",
  "genreList": [{"id": "888L"}]
}

### Book
GET localhost:8080/book
Accept: application/json

###
POST localhost:8080/book
Content-Type: application/json

{
  "title": "BookTitle.TestRest",
  "authorList": [{"id": "A1"}, {"id": "A2"}],
  "genre": {"id": "2"},
  "description": "BookDescriooption.TestRest"
}

###

