### flux genre list
GET localhost:8080/flux/genre
Accept: application/json, text/event-stream

### flux genre id
GET localhost:8080/flux/genre/1
Accept: application/json

### flux genre add
POST localhost:8080/flux/genre
#Content-Type: application/json
Accept: application/json, text/event-stream
#Accept: application/json

{
  "name":"GenreName.TestFluxRest",
  "description":"GenreDescription.TestFluxRest"
}

###############################################################
### author list

### flux author list
GET localhost:8080/flux/author
Accept: text/event-stream

### flux author get
GET localhost:8080/flux/author/A1
Accept: text/event-stream

### flux author add
POST localhost:8080/flux/author
Accept: application/json, text/event-stream

{
  "firstName": "Firstname.TestRest",
  "lastName": "Lastname.TestRest",
  "surName": "Surname.TestRest",
  "genreList": [{"id": "888L"}]
}

######################################################################
### Book
GET localhost:8080/flux/book
Accept: application/json
#Accept: text/event-stream

###
POST localhost:8080/book
Content-Type: application/json

{
  "title": "BookTitle.TestRest",
  "authorList": [{"id": "A1"}, {"id": "A2"}],
  "genre": {"id": "2"},
  "description": "BookDescriooption.TestRest"
}

###

