spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  #
  shell:
    interactive:
      enabled: false
  data:
    mongodb:
      database: testdb

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    data: testdata.sql


#
messages:
  language: "en"
  country: "GB"
  bundle: "/messages/app_message"
# DB access
pool:
  jdbcDriver: org.postgresql.Driver
  jdbcString: jdbc:postgresql://localhost:5432/otus
  jdbcUser: postgres
  jdbcPassword: postgres
